
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: StorageModule
// ---------------------------------------------

#ifndef STORAGEMODULE_H
#define STORAGEMODULE_H

#include <Arduino.h>
#include <FS.h>
#include <LittleFS.h>
#include <ArduinoJson.h>

#define FORMAT_LITTLEFS_IF_FAILED true
#define FLASH LittleFS

class StorageModule
{
public:
    // accessible from outside the class
    StorageModule();  // constructor
    ~StorageModule(); // destructor

    bool begin();

    bool readFile(String path, String &content);
    bool readFile(String path, JsonDocument &document);

    bool writeFile(String path, String content);
    bool writeFile(String path, JsonDocument document);

    void deleteFile(String path);

    void createDir(String path);

    String filePath(String type, int year, int month, int day);

    int countFiles(String path);

    JsonDocument listFiles(String path);
    String getFileList(String path);

    size_t getUsedBytes();
    size_t getTotalBytes();

protected:
    // cannot be accessed from outside the class, however, they can be accessed in inherited classes
private:
};

#endif
