
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: StorageModule
// ---------------------------------------------

#include "StorageModule.h"

/**
 * @brief Constructor for StorageModule
 *
 */
StorageModule::StorageModule()
{
}

/**
 * @brief begin
 * Destructor for StorageModule
 */
StorageModule::~StorageModule()
{
}

/**
 * @brief begin
 * Initialize the storage, format if failed
 */
bool StorageModule::begin()
{
	return FLASH.begin(FORMAT_LITTLEFS_IF_FAILED);
}

/**
 * Read the file content
 * @param path the file path (should start with /)
 * @param content the string to read data into
 * @return true if the file was read or false if doesn't exist
 */
bool StorageModule::readFile(String path, String &content)
{
	File file = FLASH.open(path, "r");
	if (!file)
	{
		return false;
	}
	content = file.readString();
	file.close();
	return true;
}

/**
 * Read the file content to a JsonDocument
 * @param path the file path (should start with /)
 * @param document the jsondocument
 * @return true if the file was read and deserialized correctly
 */
bool StorageModule::readFile(String path, JsonDocument &document)
{
	String content;
	if (readFile(path, content))
	{
		DeserializationError error = deserializeJson(document, content);
		if (!error)
		{
			return true;
		}
	}
	return false;
}

/**
 * Write content to the file content
 * @param path the file path (should start with /)
 * @param content the string to write
 * @return true if the file was written or false if failed
 */
bool StorageModule::writeFile(String path, String content)
{
	File file = FLASH.open(path, "w");
	if (!file)
	{
		return false;
	}
	file.print(content);
	file.close();
	return true;
}

/**
 * Write json document to the file content
 * @param path the file path (should start with /)
 * @param document the document to write
 * @return true if the file was written or false if failed
 */
bool StorageModule::writeFile(String path, JsonDocument document)
{
	String content;
	serializeJson(document, content);
	return writeFile(path, content);
}

/**
 * Create a file path based on date (For Steps & Battery records)
 * @param type folder path eg /steps
 * @param year year
 * @param month month
 * @param day day
 * @return file path eg /steps/2025-10-18.txt
 */
String StorageModule::filePath(String type, int year, int month, int day)
{
	char buf[20];
	snprintf(buf, sizeof(buf), "/%04d-%02d-%02d.txt", year, month, day);
	return type + String(buf);
}

/**
 * List the files in a path
 * @param path the path
 * @return string with file list
 */
String StorageModule::getFileList(String path)
{
	String fileList;
	File dir = FLASH.open(path);

	if (!dir || !dir.isDirectory())
	{
		return "Path not a directory: " + path;
	}

	fileList += "Listing for: " + path + "\n";
	// fileList += "--------------------------\n";

	File entry;
	while ((entry = dir.openNextFile()))
	{
		String entryName = entry.name();
		if (entry.isDirectory())
		{
			fileList += "[D]  " + entryName + "\n";
			// Recursively list subdirectory
			// fileList += getFileList("/" + entryName);
		}
		else
		{
			fileList += "[F] " + entryName + " (" + String(entry.size()) + " bytes)\n";
		}
		entry.close();
	}

	// fileList += "--------------------------\n";
	return fileList;
}

/**
 * List the files in a path
 * @param path the path
 * @return the json array with the file paths
 */
JsonDocument StorageModule::listFiles(String path)
{
	JsonDocument array;
	File dir = FLASH.open(path);
	if (!dir || !dir.isDirectory())
	{
		return array;
	}

	File entry;
	while ((entry = dir.openNextFile()))
	{
		String entryName = entry.name();
		if (!entry.isDirectory())
		{
			array.add(path + "/" + entryName);
		}
		entry.close();
	}
	return array;
}

/**
 * Count number of files in a path excluding directories
 * @param path the path
 * @return number of files
 */
int StorageModule::countFiles(String path)
{
	File dir = FLASH.open(path);
	if (!dir || !dir.isDirectory())
	{
		return -1;
	}
	File entry;
	int count = 0;
	while ((entry = dir.openNextFile()))
	{
		String entryName = entry.name();
		if (!entry.isDirectory())
		{
			count++;
		}
		entry.close();
	}
	return count;
}

/**
 * Create a directory if it doesn't exist
 * @param path directory path
 */
void StorageModule::createDir(String path)
{
	if (!FLASH.exists(path))
	{
		FLASH.mkdir(path);
	}
}

/**
 * Delete a file
 * @param path the file path
 */
void StorageModule::deleteFile(String path)
{
	FLASH.remove(path);
}

/**
 * Get the number of bytes used in the flash storage
 * @return number of used bytes
 */
size_t StorageModule::getUsedBytes()
{
	return FLASH.usedBytes();
}

/**
 * Get the number of total bytes in the flash storage
 * @return number of total bytes
 */
size_t StorageModule::getTotalBytes()
{
	return FLASH.totalBytes();
}
