
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: HealthModule
// ---------------------------------------------

#ifndef HEALTHMODULE_H
#define HEALTHMODULE_H

#include <ChronosESP32.h>
#include <ArduinoJson.h>

#include "StorageModule.h"

#define USER_FILE "/user.json"

#define STEPS_FOLDER "/steps"

typedef struct
{
    uint8_t age;        // in years
    uint8_t height;     // in cm
    uint8_t weight;     // in kg
    uint8_t stepLength; // in cm
    uint32_t targetSteps;
} UserInfo;

class HealthModule
{
public:
    // accessible from outside the class
    HealthModule(ChronosESP32 &watch, StorageModule &storage); // constructor
    ~HealthModule();                                           // destructor

    void begin();
    void update();

    void setUserInfo(uint8_t age, uint8_t height, uint8_t weight, uint8_t stepLength, uint32_t targetSteps);

    void syncRealtime(uint32_t steps);
    void syncData();

    String userInfoToJson();

    uint32_t calculateCalories(uint32_t steps);
    float calculateDistance(uint32_t steps, bool metric);

    void saveHourlyStepCount(int year, int month, int day, int hour, uint32_t steps);
    String readDailyStepCount(int year, int month, int day);
    String getDailyStepCounts(int year, int month, int day);

protected:
    // cannot be accessed from outside the class, however, they can be accessed in inherited classes
private:
    ChronosESP32 &mWatch;
    StorageModule &mStorage;
    UserInfo mUserInfo;
};

#endif
