
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: HealthModule
// ---------------------------------------------

#include "HealthModule.h"

/**
 * @brief Constructor for HealthModule
 * @param watch Reference to Chronos ESP32 watch instance
 * @param storage Reference to Storage Module instance
 */
HealthModule::HealthModule(ChronosESP32 &watch, StorageModule &storage) : mWatch(watch), mStorage(storage)
{
	mUserInfo.age = 25;		   // in years
	mUserInfo.height = 175;	   // in cm
	mUserInfo.weight = 70;	   // in kg
	mUserInfo.stepLength = 70; // in cm
	mUserInfo.targetSteps = 5000;
}

/**
 * @brief Destructor for HealthModule
 *
 */
HealthModule::~HealthModule()
{
}

/**
 * @brief begin
 * Read user info from storage
 */
void HealthModule::begin()
{
	JsonDocument doc;
	if (mStorage.readFile(USER_FILE, doc))
	{
		mUserInfo.age = doc["age"] | mUserInfo.age;
		mUserInfo.height = doc["height"] | mUserInfo.height;
		mUserInfo.weight = doc["weight"] | mUserInfo.weight;
		mUserInfo.stepLength = doc["stepLength"] | mUserInfo.stepLength;
		mUserInfo.targetSteps = doc["targetSteps"] | mUserInfo.targetSteps;
	}
}

/**
 * @brief update
 *
 */
void HealthModule::update()
{
}

/**
 * Write the user info received from Chronos App via BLE to storage
 * @param age age
 * @param height height (cm)
 * @param weight weight (kg)
 * @param stepLength step length (cm)
 * @param targetSteps target steps per day
 */
void HealthModule::setUserInfo(uint8_t age, uint8_t height, uint8_t weight, uint8_t stepLength, uint32_t targetSteps)
{
	mUserInfo.age = age;
	mUserInfo.height = height;
	mUserInfo.weight = weight;
	mUserInfo.stepLength = stepLength;
	mUserInfo.targetSteps = targetSteps;

	String userInfoJson = userInfoToJson();
	mStorage.writeFile(USER_FILE, userInfoJson);
}

/**
 * Sync the current steps data to the Chronos app
 * @param steps current steps reading
 */
void HealthModule::syncRealtime(uint32_t steps)
{
	float calories = calculateCalories(steps);
	mWatch.sendRealtimeSteps(steps, (uint32_t)calories);
}

/**
 * Sync stored data to Chronos App, this will be saved in the app. Records on ESP32 storage may be deleted if needed
 */
void HealthModule::syncData()
{

	String stepData = readDailyStepCount(mWatch.getYear(), mWatch.getMonth() + 1, mWatch.getDay());
	JsonDocument doc;
	DeserializationError error = deserializeJson(doc, stepData);
	if (!error)
	{
		uint32_t year = doc["year"].as<uint32_t>();
		uint8_t month = doc["month"].as<uint8_t>();
		uint8_t day = doc["day"].as<uint8_t>();
		for (int hour = 0; hour < 24; hour++)
		{
			uint32_t hourlySteps = doc[String(hour)].as<uint32_t>();
			if (hourlySteps > 0)
			{
				float hourlyCalories = calculateCalories(hourlySteps);
				mWatch.sendStepsRecord(hourlySteps, (uint32_t)hourlyCalories, hour, day, month, year);
			}
		}
	}
}

/**
 * Estimate the calories burnt using steps and user info
 * @param steps steps
 * @return the calories
 */
uint32_t HealthModule::calculateCalories(uint32_t steps)
{
	// Simple calorie calculation based on steps and user weight
	// This is a rough estimate and can be improved with more accurate formulas
	float distance_km = (steps * mUserInfo.stepLength) / 100000.0; // Convert cm to km
	float calories_per_km_per_kg = 1.036;						   // Average calories burned per km per kg of body weight
	return (uint32_t)(distance_km * mUserInfo.weight * calories_per_km_per_kg);
}

/**
 * Estimate the distance covered using steps and user info step length
 * @param steps steps
 * @param metric is metric unit
 * @return the distance in km or miles
 */
float HealthModule::calculateDistance(uint32_t steps, bool metric)
{
	// Step length assumed in centimeters
	float distanceKm = (steps * mUserInfo.stepLength) / 100000.0f; // cm → km

	if (metric)
		return distanceKm;

	// Convert kilometers to miles
	return distanceKm * 0.621371f;
}

/**
 * Get the user info json as a string
 * @return the json string
 */
String HealthModule::userInfoToJson()
{
	JsonDocument doc;
	doc["age"] = mUserInfo.age;
	doc["height"] = mUserInfo.height;
	doc["weight"] = mUserInfo.weight;
	doc["stepLength"] = mUserInfo.stepLength;
	doc["targetSteps"] = mUserInfo.targetSteps;

	String jsonString;
	serializeJson(doc, jsonString);
	return jsonString;
}

/**
 * Save the hourly steps to storage
 * @param year year
 * @param month month
 * @param day day
 * @param hour hour
 * @param steps steps
 */
void HealthModule::saveHourlyStepCount(int year, int month, int day, int hour, uint32_t steps)
{
	mStorage.createDir(STEPS_FOLDER);
	String path = mStorage.filePath(STEPS_FOLDER, year, month, day);
	String content;
	JsonDocument doc;
	if (mStorage.readFile(path, content))
	{
		// file exists, parse JSON
		DeserializationError error = deserializeJson(doc, content);
	}
	doc[String(hour)] = steps;

	mStorage.writeFile(path, doc);
}

/**
 * Read the steps records from storage
 * @param year year
 * @param month month
 * @param day day
 * @param hour hour
 * @return the json string with the data
 */
String HealthModule::readDailyStepCount(int year, int month, int day)
{
	String path = mStorage.filePath(STEPS_FOLDER, year, month, day);
	String content;
	JsonDocument doc;
	uint32_t totalSteps = 0;
	if (mStorage.readFile(path, content))
	{
		// file exists, parse JSON
		DeserializationError error = deserializeJson(doc, content);
		if (!error)
		{

			for (JsonPair kv : doc.as<JsonObject>())
			{
				totalSteps += kv.value().as<uint32_t>();
			}
		}
	}
	doc["day"] = day;
	doc["month"] = month;
	doc["year"] = year;
	doc["totalSteps"] = totalSteps;
	serializeJson(doc, content);
	return content;
}

/**
 * Read the steps records from storage
 * @param year year
 * @param month month
 * @param day day
 * @param hour hour
 * @return the json string with the data
 */
String HealthModule::getDailyStepCounts(int year, int month, int day)
{
	String path = mStorage.filePath(STEPS_FOLDER, year, month, day);
	String content;
	if (mStorage.readFile(path, content))
	{
		return content;
	}
	return "{}"; // return empty JSON object if file doesn't exist
}
